api_credentials: bitvavo_api_key.json
buy_drop_pct: -2.5
dashboard_host: 0.0.0.0
dashboard_port: 8000
db_path: ../data/trades.db
dev_sleep_hours: 4
email:
  enabled: false
  password: ""
  to: ""
  username: ""
exchange: bitvavo
invest_eur: 50.0
live_trading: true
log_path: ../data/aurono_log.txt
mode: live
pair: BTCEUR
sell_rise_pct: 2.1
log_level: INFO
